# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_usb_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
<<<<<<< HEAD
    { device = "/dev/disk/by-uuid/c900ac5f-22d8-46b5-8b44-127c5dce1976";
=======
    { device = "/dev/disk/by-uuid/8a7d86c5-7bb3-4fe8-a1f0-a57916af4090";
>>>>>>> 7f5db9b7f084e2873c5b077b77e4a2677f8c6e9a
      fsType = "ext4";
    };

  fileSystems."/boot" =
<<<<<<< HEAD
    { device = "/dev/disk/by-uuid/8EB4-4D09";
=======
    { device = "/dev/disk/by-uuid/9C64-FC08";
>>>>>>> 7f5db9b7f084e2873c5b077b77e4a2677f8c6e9a
      fsType = "vfat";
    };

  swapDevices =
<<<<<<< HEAD
    [ { device = "/dev/disk/by-uuid/b953598b-2576-4302-86e6-328dcd34be02"; }
=======
    [ { device = "/dev/disk/by-uuid/67735f2e-ac21-41b3-8707-8d3a53e78c8d"; }
>>>>>>> 7f5db9b7f084e2873c5b077b77e4a2677f8c6e9a
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
